#! /bin/bash

rosdep update || exit 1

# BUG ?
# rosdep check return 0 when just key can't resolved ?
# but rosdep install return 1 ?
# rosdep check return 1 only when resolved pkg hasn't installed ?

# Every build/exec depend key must be resolved except src packages
# Note: git-bloom-generate can transform keys in src packages !
# So git-bloom-release succeed in transforming key to control file
# Then create the debian source-package(build/exec depends) for each pkg
rosdep check --from-paths . --ignore-src 2>&1 >/dev/null | grep "ERROR\[" && exit 1
exit 0
