#! /bin/bash

version=$1

for pkg in $(catkin_topological_order --only-folders); do
	xml=$pkg/package.xml
	sed -i -e "/<version>/,/<\/version>/ s|<version>[0-9a-z.]\{1,\}</version>|<version>${version}</version>|g" $xml
done

