#! /bin/bash

if (( $# != 1 )); then
	echo "Usage: gbp-release-build release-repo"
	exit 1
fi
cd $1 || exit 1

if which git-buildpackage; then
	build_comm="git-buildpackage"
elif which gbp; then
	build_comm="gbp buildpackage"
else
	echo "No git-buildpackage/gbp, sudo apt-get install -y git-buildpackage"
fi
BRANCHES=$(git branch | grep "\sdebian/kinetic/$(lsb_release -cs)/")
for BRANCH in ${BRANCHES}
do
  echo "branch: $BRANCH"
  if ! git checkout ${BRANCH}; then
	  echo "Git checkout $BRANCH failed"
	  exit 1
  fi
  git clean -df
  #git-buildpackage -uc -us  --git-ignore-new
  # builds your package in a vacuum, setting up an empty change root and installing only the packages you depend on
  #gbp buildpackage -uc -us --git-ignore-branch --git-ignore-new --git-pbuilder &> ../build.log || exit 1
  if ! gbp buildpackage -uc -us --git-ignore-branch --git-ignore-new &> ../build.log; then
	  echo "git-buildpackage $BRANCH failed"
	  exit 1
  fi

  # restore the debian release branch, or checkout fail
  git reset --hard
  git clean -df
done

